# -*- coding: utf-8 -*-
"""Jawaban Soal - Kenza.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uDUmSxwR0iM-sAUWVj3UTlrOOFFCkz6I
"""

#Soal 1

def fpb(a,b):
    if a<b:
        smaller=a
    else:
        smaller=b
    for i in range (1,smaller+1):
        if a%i==0 and b%i==0:
            fpb=i
        # else:
        #     continue
    return fpb

def kpk(a,b):
    kpk=int(a*b/fpb(a,b))
    return kpk

a=int(input('Ketik angka pertama :'))
b=int(input('Ketik angka kedua   :'))

print('FPB dari ',a,' dan ',b,' adalah ',fpb(a,b))
print('KPK dari ',a,' dan ',b,' adalah ',kpk(a,b))

#Soal 2

angka = int(input('Ketik angka: '))

list_bilangan = ['bulat']

if angka < 0:
    list_bilangan.append('negatif')
else:
    list_bilangan.append('cacah')
    if angka == 0:
        list_bilangan.append('nol')
    else:
        list_bilangan.append('asli')
        if angka %2 != 0:
            list_bilangan.append('ganjil')
            if angka > 1:
                for i in range(2, angka):
                    if angka % i == 0:
                        list_bilangan.append('komposit')
                        break
                else:
                    list_bilangan.append('prima')
                    
        else:
            list_bilangan.append('genap')
            for i in range(2, angka):
                if angka % i == 0:
                    list_bilangan.append('komposit')
                    break
            else:
                list_bilangan.append('prima')
                
print(list_bilangan)

#Soal 3

# API key: 02fb395c7d6544689eacde0eccc8f25d

# from newsapi import NewsApiClient

# # init
# newsapi = NewsApiClient(api_key = '02fb395c7d6544689eacde0eccc8f25d')

# # /v2/top-headlines
# top_headlines = newsapi.get_top_headlines(q='bitcoin',
#                                           sources='bbc-news,the-verge',
#                                           category='business',
#                                           language='en',
#                                           country='us')

import requests

api_key = '02fb395c7d6544689eacde0eccc8f25d'
kategori = {
    '1': 'technology',
    '2': 'business',
    '3': 'sports',
    '4': 'health',
    '5': 'science'
}

print('Selamat datang, mau tahu berita apa hari ini?')
print('[1] Berita seputar teknologi')
print('[2] Berita seputar bisnis')
print('[3] Berita seputar olahraga')
print('[4] Berita seputar kesehatan')
print('[5] Berita seputar science')

pilih = input('Ketik pilihan anda [1/2/3/4/5]: ')
berita = kategori[pilih]

url = 'https://newsapi.org/v2/top-headlines?country=id&category='+berita+'&apiKey='+api_key

articles = requests.get(url)

print('Berikut adalah top 5 berita Indonesia bidang {}:'.format(kategori[pilih]))

i = 0

while i < 5:
    print('{} - {}'.format(i+1, articles.json()['articles'][i]['title']))
    i += 1